### ISSUE TITLE
Multiple warnings ('... accessing non-existent properties of module exports')

### ISSUE THREAD

**Issue by Askelkana** [Nordstrom/config#21]
`'Warning: Accessing non-existent property 'cat' of module exports inside circular dependency'` - Just the first of many warnings of all the properties of 'module exports'.

Occurs in Node 14.4.0 (latest stable build at time of reporting). Does not occur in Node 11.11.0, so somewhere inbetween Node has changed.

First noticed the warnings in my own project after updating Node. Checked the package's tests. Reproduced.

**Comment by Askelkana** [comment]
Hmmm, not sure what happened, but now I cannot reproduce this, other than reinstalled node (via nvm). Closing.

**Comment by stefanocudini** [comment]
I have same problem :(
